### ISSUE TITLE
hi bro, i got some error

### ISSUE THREAD

**Issue by guanshiang** [5663015/segment_anything_webui#3]
Traceback (most recent call last):
  File "D:\AI\segment-anything\segment_anything_webui\app.py", line 156, in <module>
    input_image.select(
AttributeError: 'Image' object has no attribute 'select'

**Comment by 5663015** [comment]
The version of Gradio may not be right. It should be `gradio==3.25.0`.

**Comment by guanshiang** [comment]
> 
C:\ProgramData\Anaconda3\envs\segmentany\lib\site-packages\gradio\utils.py:875: UserWarning: Expected 14 arguments for function <function run_inference at 0x00000229167C83A0>, received 13.
  warnings.warn(
C:\ProgramData\Anaconda3\envs\segmentany\lib\site-packages\gradio\utils.py:879: UserWarning: Expected at least 14 arguments for function <function run_inference at 0x00000229167C83A0>, received 13.
  warnings.warn(
Traceback (most recent call last):
  File "D:\AI\test\segment_anything_webui\app.py", line 189, in <module>
    button_video.click(run_inference, inputs=[device, model_type, points_per_side, pred_iou_thresh, stability_score_thresh,
  File "C:\ProgramData\Anaconda3\envs\segmentany\lib\site-packages\gradio\blocks.py", line 1285, in __exit__
    self.config = self.get_config_file()
  File "C:\ProgramData\Anaconda3\envs\segmentany\lib\site-packages\gradio\blocks.py", line 1261, in get_config_file
    "input": list(block.input_api_info()),  # type: ignore
  File "C:\ProgramData\Anaconda3\envs\segmentany\lib\site-packages\gradio_client\serializing.py", line 41, in input_api_info
    return (api_info["serialized_input"][0], api_info["serialized_input"][1])
KeyError: 'serialized_input'
