### ISSUE TITLE
KeyError: 'type'

### ISSUE THREAD

**Issue by shomeAvataar** [5663015/segment_anything_webui#6]
The version of gradio is am using is : 3.25.0. Still O get error
I am getting error while running: segment_anything_webui:

when I run python app.py, I get

Traceback (most recent call last):
  File "/home/neo/Desktop/shome/mesh_related/mesh_FG_BG_segmentation/codes/segment_anything_webui/app.py", line 189, in <module>
    button_video.click(run_inference, inputs=[device, model_type, points_per_side, pred_iou_thresh, stability_score_thresh,
  File "/home/neo/miniconda3/envs/shome_SAM_py39/lib/python3.9/site-packages/gradio/blocks.py", line 1285, in __exit__
    self.config = self.get_config_file()
  File "/home/neo/miniconda3/envs/shome_SAM_py39/lib/python3.9/site-packages/gradio/blocks.py", line 1261, in get_config_file
    "input": list(block.input_api_info()),  # type: ignore
  File "/home/neo/miniconda3/envs/shome_SAM_py39/lib/python3.9/site-packages/gradio_client/serializing.py", line 44, in input_api_info
    types = api_info.get("serialized_input", [api_info["info"]["type"]] * 2)  # type: ignore
KeyError: 'type

**Comment by freya9933** [comment]
I'm having the same problem, have you solved it already? @shomeAvataar

**Comment by buptlj** [comment]
pip install  gradio==3.50.0

**Comment by webbrain-one** [comment]
Hi! I've opened a pull request to address this `KeyError: 'type'` issue. You can check out the fix here: https://github.com/5663015/segment_anything_webui/pull/7
